//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtestcollection.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardDataListOfBusLocationModel", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class StandardDataListOfBusLocationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webtestcollection.ServiceReference1.BusLocationModel[] listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public webtestcollection.ServiceReference1.BusLocationModel[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.timeStampField, value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusLocationModel", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class BusLocationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lineTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.lineTypeField, value) != true)) {
                    this.lineTypeField = value;
                    this.RaisePropertyChanged("lineType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                if ((object.ReferenceEquals(this.distanceField, value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardDataListOfLineModel", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class StandardDataListOfLineModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webtestcollection.ServiceReference1.LineModel[] listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public webtestcollection.ServiceReference1.LineModel[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.timeStampField, value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineModel", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class LineModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offRunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lineTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webtestcollection.ServiceReference1.StationModel[] stationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.departureTimeField, value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string offRunningTime {
            get {
                return this.offRunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.offRunningTimeField, value) != true)) {
                    this.offRunningTimeField = value;
                    this.RaisePropertyChanged("offRunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.lineTypeField, value) != true)) {
                    this.lineTypeField = value;
                    this.RaisePropertyChanged("lineType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public webtestcollection.ServiceReference1.StationModel[] stations {
            get {
                return this.stationsField;
            }
            set {
                if ((object.ReferenceEquals(this.stationsField, value) != true)) {
                    this.stationsField = value;
                    this.RaisePropertyChanged("stations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationModel", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class StationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webtestcollection.ServiceReference1.GPSPoint gpsPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string station {
            get {
                return this.stationField;
            }
            set {
                if ((object.ReferenceEquals(this.stationField, value) != true)) {
                    this.stationField = value;
                    this.RaisePropertyChanged("station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stationNumber {
            get {
                return this.stationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.stationNumberField, value) != true)) {
                    this.stationNumberField = value;
                    this.RaisePropertyChanged("stationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public webtestcollection.ServiceReference1.GPSPoint gpsPoint {
            get {
                return this.gpsPointField;
            }
            set {
                if ((object.ReferenceEquals(this.gpsPointField, value) != true)) {
                    this.gpsPointField = value;
                    this.RaisePropertyChanged("gpsPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GPSPoint", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class GPSPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardDataListOfBusDepartureModelLine", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class StandardDataListOfBusDepartureModelLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private webtestcollection.ServiceReference1.BusDepartureModelLine[] listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public webtestcollection.ServiceReference1.BusDepartureModelLine[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.timeStampField, value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusDepartureModelLine", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class BusDepartureModelLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finalStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offRunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lineTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string finalStation {
            get {
                return this.finalStationField;
            }
            set {
                if ((object.ReferenceEquals(this.finalStationField, value) != true)) {
                    this.finalStationField = value;
                    this.RaisePropertyChanged("finalStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.departureTimeField, value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string offRunningTime {
            get {
                return this.offRunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.offRunningTimeField, value) != true)) {
                    this.offRunningTimeField = value;
                    this.RaisePropertyChanged("offRunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                if ((object.ReferenceEquals(this.intervalField, value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lineType {
            get {
                return this.lineTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.lineTypeField, value) != true)) {
                    this.lineTypeField = value;
                    this.RaisePropertyChanged("lineType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardData", Namespace="http://10628106.com/bus")]
    [System.SerializableAttribute()]
    public partial class StandardData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.timeStampField, value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10628106.com/bus", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://10628106.com/bus 的元素名称 busLine 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getBusLocation", ReplyAction="*")]
        webtestcollection.ServiceReference1.getBusLocationResponse getBusLocation(webtestcollection.ServiceReference1.getBusLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getBusLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusLocationResponse> getBusLocationAsync(webtestcollection.ServiceReference1.getBusLocationRequest request);
        
        // CODEGEN: 命名空间 http://10628106.com/bus 的元素名称 busLine 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getTodayLineInfo", ReplyAction="*")]
        webtestcollection.ServiceReference1.getTodayLineInfoResponse getTodayLineInfo(webtestcollection.ServiceReference1.getTodayLineInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getTodayLineInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getTodayLineInfoResponse> getTodayLineInfoAsync(webtestcollection.ServiceReference1.getTodayLineInfoRequest request);
        
        // CODEGEN: 命名空间 http://10628106.com/bus 的元素名称 busLine 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getBusDepartureSchedule", ReplyAction="*")]
        webtestcollection.ServiceReference1.getBusDepartureScheduleResponse getBusDepartureSchedule(webtestcollection.ServiceReference1.getBusDepartureScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/getBusDepartureSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusDepartureScheduleResponse> getBusDepartureScheduleAsync(webtestcollection.ServiceReference1.getBusDepartureScheduleRequest request);
        
        // CODEGEN: 命名空间 http://10628106.com/bus 的元素名称 channelNumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/GetAllBusLocation", ReplyAction="*")]
        webtestcollection.ServiceReference1.GetAllBusLocationResponse GetAllBusLocation(webtestcollection.ServiceReference1.GetAllBusLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/GetAllBusLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLocationResponse> GetAllBusLocationAsync(webtestcollection.ServiceReference1.GetAllBusLocationRequest request);
        
        // CODEGEN: 命名空间 http://10628106.com/bus 的元素名称 channelNumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/GetAllBusLine", ReplyAction="*")]
        webtestcollection.ServiceReference1.GetAllBusLineResponse GetAllBusLine(webtestcollection.ServiceReference1.GetAllBusLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10628106.com/bus/GetAllBusLine", ReplyAction="*")]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLineResponse> GetAllBusLineAsync(webtestcollection.ServiceReference1.GetAllBusLineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBusLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBusLocation", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getBusLocationRequestBody Body;
        
        public getBusLocationRequest() {
        }
        
        public getBusLocationRequest(webtestcollection.ServiceReference1.getBusLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getBusLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busLine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lineType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string channelNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string channelEncodedKey;
        
        public getBusLocationRequestBody() {
        }
        
        public getBusLocationRequestBody(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey) {
            this.busLine = busLine;
            this.stationName = stationName;
            this.lineType = lineType;
            this.channelNumber = channelNumber;
            this.channelEncodedKey = channelEncodedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBusLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBusLocationResponse", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getBusLocationResponseBody Body;
        
        public getBusLocationResponse() {
        }
        
        public getBusLocationResponse(webtestcollection.ServiceReference1.getBusLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getBusLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webtestcollection.ServiceReference1.StandardDataListOfBusLocationModel getBusLocationResult;
        
        public getBusLocationResponseBody() {
        }
        
        public getBusLocationResponseBody(webtestcollection.ServiceReference1.StandardDataListOfBusLocationModel getBusLocationResult) {
            this.getBusLocationResult = getBusLocationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTodayLineInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTodayLineInfo", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getTodayLineInfoRequestBody Body;
        
        public getTodayLineInfoRequest() {
        }
        
        public getTodayLineInfoRequest(webtestcollection.ServiceReference1.getTodayLineInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getTodayLineInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busLine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channelNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string channelEncodedKey;
        
        public getTodayLineInfoRequestBody() {
        }
        
        public getTodayLineInfoRequestBody(string busLine, string channelNumber, string channelEncodedKey) {
            this.busLine = busLine;
            this.channelNumber = channelNumber;
            this.channelEncodedKey = channelEncodedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTodayLineInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTodayLineInfoResponse", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getTodayLineInfoResponseBody Body;
        
        public getTodayLineInfoResponse() {
        }
        
        public getTodayLineInfoResponse(webtestcollection.ServiceReference1.getTodayLineInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getTodayLineInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webtestcollection.ServiceReference1.StandardDataListOfLineModel getTodayLineInfoResult;
        
        public getTodayLineInfoResponseBody() {
        }
        
        public getTodayLineInfoResponseBody(webtestcollection.ServiceReference1.StandardDataListOfLineModel getTodayLineInfoResult) {
            this.getTodayLineInfoResult = getTodayLineInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBusDepartureScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBusDepartureSchedule", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getBusDepartureScheduleRequestBody Body;
        
        public getBusDepartureScheduleRequest() {
        }
        
        public getBusDepartureScheduleRequest(webtestcollection.ServiceReference1.getBusDepartureScheduleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getBusDepartureScheduleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busLine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channelNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string channelEncodedKey;
        
        public getBusDepartureScheduleRequestBody() {
        }
        
        public getBusDepartureScheduleRequestBody(string busLine, string channelNumber, string channelEncodedKey) {
            this.busLine = busLine;
            this.channelNumber = channelNumber;
            this.channelEncodedKey = channelEncodedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBusDepartureScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBusDepartureScheduleResponse", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.getBusDepartureScheduleResponseBody Body;
        
        public getBusDepartureScheduleResponse() {
        }
        
        public getBusDepartureScheduleResponse(webtestcollection.ServiceReference1.getBusDepartureScheduleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class getBusDepartureScheduleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webtestcollection.ServiceReference1.StandardDataListOfBusDepartureModelLine getBusDepartureScheduleResult;
        
        public getBusDepartureScheduleResponseBody() {
        }
        
        public getBusDepartureScheduleResponseBody(webtestcollection.ServiceReference1.StandardDataListOfBusDepartureModelLine getBusDepartureScheduleResult) {
            this.getBusDepartureScheduleResult = getBusDepartureScheduleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBusLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBusLocation", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.GetAllBusLocationRequestBody Body;
        
        public GetAllBusLocationRequest() {
        }
        
        public GetAllBusLocationRequest(webtestcollection.ServiceReference1.GetAllBusLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class GetAllBusLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string channelNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channelEncodedKey;
        
        public GetAllBusLocationRequestBody() {
        }
        
        public GetAllBusLocationRequestBody(string channelNumber, string channelEncodedKey) {
            this.channelNumber = channelNumber;
            this.channelEncodedKey = channelEncodedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBusLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBusLocationResponse", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.GetAllBusLocationResponseBody Body;
        
        public GetAllBusLocationResponse() {
        }
        
        public GetAllBusLocationResponse(webtestcollection.ServiceReference1.GetAllBusLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class GetAllBusLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webtestcollection.ServiceReference1.StandardData GetAllBusLocationResult;
        
        public GetAllBusLocationResponseBody() {
        }
        
        public GetAllBusLocationResponseBody(webtestcollection.ServiceReference1.StandardData GetAllBusLocationResult) {
            this.GetAllBusLocationResult = GetAllBusLocationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBusLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBusLine", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.GetAllBusLineRequestBody Body;
        
        public GetAllBusLineRequest() {
        }
        
        public GetAllBusLineRequest(webtestcollection.ServiceReference1.GetAllBusLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class GetAllBusLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string channelNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channelEncodedKey;
        
        public GetAllBusLineRequestBody() {
        }
        
        public GetAllBusLineRequestBody(string channelNumber, string channelEncodedKey) {
            this.channelNumber = channelNumber;
            this.channelEncodedKey = channelEncodedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBusLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBusLineResponse", Namespace="http://10628106.com/bus", Order=0)]
        public webtestcollection.ServiceReference1.GetAllBusLineResponseBody Body;
        
        public GetAllBusLineResponse() {
        }
        
        public GetAllBusLineResponse(webtestcollection.ServiceReference1.GetAllBusLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10628106.com/bus")]
    public partial class GetAllBusLineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webtestcollection.ServiceReference1.StandardData GetAllBusLineResult;
        
        public GetAllBusLineResponseBody() {
        }
        
        public GetAllBusLineResponseBody(webtestcollection.ServiceReference1.StandardData GetAllBusLineResult) {
            this.GetAllBusLineResult = GetAllBusLineResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : webtestcollection.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<webtestcollection.ServiceReference1.ServiceSoap>, webtestcollection.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webtestcollection.ServiceReference1.getBusLocationResponse webtestcollection.ServiceReference1.ServiceSoap.getBusLocation(webtestcollection.ServiceReference1.getBusLocationRequest request) {
            return base.Channel.getBusLocation(request);
        }
        
        public webtestcollection.ServiceReference1.StandardDataListOfBusLocationModel getBusLocation(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getBusLocationRequest inValue = new webtestcollection.ServiceReference1.getBusLocationRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getBusLocationRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.stationName = stationName;
            inValue.Body.lineType = lineType;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            webtestcollection.ServiceReference1.getBusLocationResponse retVal = ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getBusLocation(inValue);
            return retVal.Body.getBusLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusLocationResponse> webtestcollection.ServiceReference1.ServiceSoap.getBusLocationAsync(webtestcollection.ServiceReference1.getBusLocationRequest request) {
            return base.Channel.getBusLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusLocationResponse> getBusLocationAsync(string busLine, string stationName, string lineType, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getBusLocationRequest inValue = new webtestcollection.ServiceReference1.getBusLocationRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getBusLocationRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.stationName = stationName;
            inValue.Body.lineType = lineType;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            return ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getBusLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webtestcollection.ServiceReference1.getTodayLineInfoResponse webtestcollection.ServiceReference1.ServiceSoap.getTodayLineInfo(webtestcollection.ServiceReference1.getTodayLineInfoRequest request) {
            return base.Channel.getTodayLineInfo(request);
        }
        
        public webtestcollection.ServiceReference1.StandardDataListOfLineModel getTodayLineInfo(string busLine, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getTodayLineInfoRequest inValue = new webtestcollection.ServiceReference1.getTodayLineInfoRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getTodayLineInfoRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            webtestcollection.ServiceReference1.getTodayLineInfoResponse retVal = ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getTodayLineInfo(inValue);
            return retVal.Body.getTodayLineInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getTodayLineInfoResponse> webtestcollection.ServiceReference1.ServiceSoap.getTodayLineInfoAsync(webtestcollection.ServiceReference1.getTodayLineInfoRequest request) {
            return base.Channel.getTodayLineInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getTodayLineInfoResponse> getTodayLineInfoAsync(string busLine, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getTodayLineInfoRequest inValue = new webtestcollection.ServiceReference1.getTodayLineInfoRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getTodayLineInfoRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            return ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getTodayLineInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webtestcollection.ServiceReference1.getBusDepartureScheduleResponse webtestcollection.ServiceReference1.ServiceSoap.getBusDepartureSchedule(webtestcollection.ServiceReference1.getBusDepartureScheduleRequest request) {
            return base.Channel.getBusDepartureSchedule(request);
        }
        
        public webtestcollection.ServiceReference1.StandardDataListOfBusDepartureModelLine getBusDepartureSchedule(string busLine, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getBusDepartureScheduleRequest inValue = new webtestcollection.ServiceReference1.getBusDepartureScheduleRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getBusDepartureScheduleRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            webtestcollection.ServiceReference1.getBusDepartureScheduleResponse retVal = ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getBusDepartureSchedule(inValue);
            return retVal.Body.getBusDepartureScheduleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusDepartureScheduleResponse> webtestcollection.ServiceReference1.ServiceSoap.getBusDepartureScheduleAsync(webtestcollection.ServiceReference1.getBusDepartureScheduleRequest request) {
            return base.Channel.getBusDepartureScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<webtestcollection.ServiceReference1.getBusDepartureScheduleResponse> getBusDepartureScheduleAsync(string busLine, string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.getBusDepartureScheduleRequest inValue = new webtestcollection.ServiceReference1.getBusDepartureScheduleRequest();
            inValue.Body = new webtestcollection.ServiceReference1.getBusDepartureScheduleRequestBody();
            inValue.Body.busLine = busLine;
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            return ((webtestcollection.ServiceReference1.ServiceSoap)(this)).getBusDepartureScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webtestcollection.ServiceReference1.GetAllBusLocationResponse webtestcollection.ServiceReference1.ServiceSoap.GetAllBusLocation(webtestcollection.ServiceReference1.GetAllBusLocationRequest request) {
            return base.Channel.GetAllBusLocation(request);
        }
        
        public webtestcollection.ServiceReference1.StandardData GetAllBusLocation(string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.GetAllBusLocationRequest inValue = new webtestcollection.ServiceReference1.GetAllBusLocationRequest();
            inValue.Body = new webtestcollection.ServiceReference1.GetAllBusLocationRequestBody();
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            webtestcollection.ServiceReference1.GetAllBusLocationResponse retVal = ((webtestcollection.ServiceReference1.ServiceSoap)(this)).GetAllBusLocation(inValue);
            return retVal.Body.GetAllBusLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLocationResponse> webtestcollection.ServiceReference1.ServiceSoap.GetAllBusLocationAsync(webtestcollection.ServiceReference1.GetAllBusLocationRequest request) {
            return base.Channel.GetAllBusLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLocationResponse> GetAllBusLocationAsync(string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.GetAllBusLocationRequest inValue = new webtestcollection.ServiceReference1.GetAllBusLocationRequest();
            inValue.Body = new webtestcollection.ServiceReference1.GetAllBusLocationRequestBody();
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            return ((webtestcollection.ServiceReference1.ServiceSoap)(this)).GetAllBusLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webtestcollection.ServiceReference1.GetAllBusLineResponse webtestcollection.ServiceReference1.ServiceSoap.GetAllBusLine(webtestcollection.ServiceReference1.GetAllBusLineRequest request) {
            return base.Channel.GetAllBusLine(request);
        }
        
        public webtestcollection.ServiceReference1.StandardData GetAllBusLine(string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.GetAllBusLineRequest inValue = new webtestcollection.ServiceReference1.GetAllBusLineRequest();
            inValue.Body = new webtestcollection.ServiceReference1.GetAllBusLineRequestBody();
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            webtestcollection.ServiceReference1.GetAllBusLineResponse retVal = ((webtestcollection.ServiceReference1.ServiceSoap)(this)).GetAllBusLine(inValue);
            return retVal.Body.GetAllBusLineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLineResponse> webtestcollection.ServiceReference1.ServiceSoap.GetAllBusLineAsync(webtestcollection.ServiceReference1.GetAllBusLineRequest request) {
            return base.Channel.GetAllBusLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<webtestcollection.ServiceReference1.GetAllBusLineResponse> GetAllBusLineAsync(string channelNumber, string channelEncodedKey) {
            webtestcollection.ServiceReference1.GetAllBusLineRequest inValue = new webtestcollection.ServiceReference1.GetAllBusLineRequest();
            inValue.Body = new webtestcollection.ServiceReference1.GetAllBusLineRequestBody();
            inValue.Body.channelNumber = channelNumber;
            inValue.Body.channelEncodedKey = channelEncodedKey;
            return ((webtestcollection.ServiceReference1.ServiceSoap)(this)).GetAllBusLineAsync(inValue);
        }
    }
}
