var commentArray=[
'put it on english please',
'"爱好"里的那个猫猫和狗狗要是能换颜色就更好了。',
'啊','我云炸学校天天不知道.',
'发型太少很多配不上',
'女生还长胡子?',
'hello',
'very good!!!!!',
'这个怎么打不开啊',
'太少衣服啦！不够穿。',
'我爱你',
'为什么没有美少女战士系列 求美少女战士呀',
'产品非常好，很喜欢！！！如果百分制的话，100000分！很有创意！好评！100000颗星！加油↖(^ω^)↗！非常看好你们哦！呵呵O(∩_∩)O~！',
'i want to read in english. :(',
'怎么加载不出来呢？？',
'加一个蘑菇头',
'脸萌好人性化，有我最爱的海贼，希望再弄多点，谢谢',
'我想加入你们的团队',
'希望可以创出拍照自动脸萌',
'Other languages',
'I like it I could do with english translation!',
'Annayfran Vidal Yarza',
'Awesome app! I d like a few more background options though , and a fez hat!',
'怎样保存图片',
'一点都不好使，人物又难看',
'this app is great',
'mm',
'赞哦！',
'魂淡游戏',
'水印太讨厌了',
'建议退出魔兽形象',
'Good!!!!!!!!!!!!',
'萌哒哒~',
'总是闪退',
'แสง',
'非常好，我用了二年了',
'希望增加更多明星元素，一定会受到用户的欢迎。',
'建议推出全家福~',
'我想要赛巴斯酱！！！！~(≧▽≦)/~',
'This app is very good, but it ll be better if we can make our portraits according to our photo.',
'太棒了！我好喜欢！',
'萌死我了',
'你們可以分享在fb嗎？',
'为什么没有深圳校服',
'国际化啦巴巴爸爸',
'(╰_╯)#',
'卡死了，坑爹',
'帽子的最後一個少了寶石帶',
'特征里面没有酒窝呀，你们要想办法了',
'来咬我啊',
'尼玛太好玩了',
'有bug',
'没有山治君的眉毛与烟',
'this app its too good, tks for creating this 👏👏💜',
'HELP ME',
'¿como se cambia el idioma?',
'i want to tell that i want it in spanish',
' i will come to you',
'burn you in flames',
'after that i will take your blood for my ritual! :-) thank you.',
'the app is fabolous:)',
'联系我 我也许能让贵公司赚大钱',
'也沒什麼拉',
'hola',
'myotee',
'español',
'为什么有的时候玩不了',
'诞节快乐机场',
'开个胡子分类啊！！！',
'祝越做越好！',
'love it!',
'Everything about this is just so cute and ughh.',
'A really cool app to like build characters and stuff',
'yeah~&awesome.',
'you can you up,no bb~',
'Wish better',
'出一些火影的吧。谢谢',
'english?',
'尊敬的脸萌工作室',
'你好，我是脸萌的一位爱好者以下是我的建议(省略5w字)',
'有更新吗',
'我擦勒~',
'希望有情侣头像制作',
'能不能三个人，？',
'hi',
'^_^; ',
'（*>.<*）~',
'( T___T )怎么会这样...',
' _( > < ) / 哇～出现了 ',
':)',
'很好，八错',
'你没，酒窝。。',
'怎么这么长时间没更新呢？',
'太棒了你们，加油！',
'挺萌',
'何时更新啊',
'我爱宝宝',
'打不开',
'我选的里面最小的脸型，但朋友们说还是胖了点。',
'都打不开，(#‵′)',
'阿狸hi',
'why isnt this in English?',
'索隆的独眼望更新，路飞的眼下伤疤也望更新，希望脸萌越办越好',
'没有虎牙啊？？！！！',
'安卓素材太少',
'真鸡巴卡',
'這app很棒',
'我爱你',
'真TM逗比',
'有木有女朋友',
'要是头发有彩色的就更好了',
'希望之後能有腳的部份:-)',
'啊，更新戳哪里',
'我的小作品',
'双人模式应该有身高差的，亲',
'嘿嘿',
'我希望有黑执事中夏尔的服饰',
'设计团队一定也是海贼迷对不对!!!',
'我想说，婚纱设计的太少了，还有我想要头纱！',
'为什么我的机型不能用 因为cpu不是主流的么',
'能不能有消防员的衣服',
'是不是可以制作马克杯啊',
'我进不聊',
'如果能多一个黑岩的就好了。',
'能多出点新的玩样儿吗？',
'对不起，我要让你上头条',
'我的没有鼻子',
'不错',
'很好玩儿！',
'你爹',
'希望增加古剑奇谭的',
'再多點萌萌噠造型',
'如果上面的人物可以换成是自己的照片，那我就大赞 了',
'真好玩，不過頭',
'我不知道怎么打邮箱，所以这样来问下，，如果是靠想象力来当设计师。。我可以不？联系方式QQ',
'好多东西没有，而且只能做正脸，希望360度哪边都能做的！',
'。。。。~还不错→_→',
'希望加一个女生撩头发的动作!',
'在不？',
'眼睛的颜色 有木有',
'😡😡怒',
'最好有一套的衣服，比如：钢铁侠的一套，有头盔和衣服',
'男女服装共用就好了',
'😁脸萌出了点问题',
'宝贝宝贝宝贝',
'多创些适合学生的啦~~~脸萌!好可爱的应用',
'应该增加，更新的提示，让我们能第一时间更新',
'能弄成t恤衫吗？价格多少啊？',
'你们这里有游戏吗？',
'点开帅哥说努力加载中然后又闪退',
'我xiang多ChUCUn几个',
'联系做一个一家三口的',
'怎麼沒有hello kitty的？很想哦！期待中...... 谢',
'德国队服是四星了，改了吧',
'求秃顶发型。。。',
'有没有人妖',
'介个…我…额……介个…就是…选择太多了，容易得选择恐惧症啊!!!…',
'嗨你們好！！我希望可以更多造型。',
'很好！希望能够再出一个可以做小动物的！！如果有，大大大赞！',
'可以增加佐助的写轮眼',
'为毛没有历史记录',
'建议提供“历史形象清除”选项',
'can we add our own 气泡',
'为什么我下载的脸萌和别人的不一样',
'希望可以出剑三的变身',
'我爱你？',
'太萌了',
'我想给我弟弟做个卡通的图片，可是找不到合适的',
'节日快乐',
'可以有双人的脸萌咩？？？',
'眉毛没有曹格女儿Grace的那种眉毛',
'总是自己关闭',
'很不错，怒赞',
'嗨 眼睛可以再美一点吗？比如说带点颜色什么的 中国风可以再多吗？',
'鹅鹅鹅鹅鹅鹅。。。',
'加个绿箭侠的变身吧！跪求！',
'我是人见人爱花见花开的人',
'这个软件虽然很好但是打不开',
'衣服里面应该把NBA 球衣全部加进去啊。',
'我要林峰发型',
'我想找真心的朋友',
'这款游戏不错！不过，你们可以多添加点一些爱好、服装啊等等。',
'怎么做了两个男人第一个就不见了',
'跪求女帝o(≧口≦)o',
'I made prince Zuko with the faceq app.',
'JUVIA thing on the new app I got!it called FaceQ',
'I did a cute thing',
'so is FaceQ what all the cool kids are using',
'cool~',
'I like this app,thx',
'I made my bf on the faceq thing omfg it was too on point',
'zoa famsz',
'在个性里 增加一个数钱的动作吧',
'how can i change the eyes colors?',
'good job',
'Great app! Fun, adorable, and addicting! ',
' The best time waster and chibi maker I have ever seen! Keep it up!',
'this is so amazing!',
'I AM ENGLISH. I SPEAK ENGLISH',
'能不能有其他日本动漫的人物，比如，柯南。谢谢',
'表情 倒数第四个 眉毛无法显示',
'能储存的图片太少了',
'加多多的啊！',
'ㅜㅊㅓㅓ하풒ㅊㅍㅎㅎ여ㅑㅇ츄ㅗㅊㄹㄹ휴ㅠㅗㅗㅜㅗㅗ혀7ㅕㅕㅓㅓㅓㅗㅗ어아대어1ㅗㅗㅠㅈ？',
'制作到一半就重来了，怎么回事',
'Poop Queen',
'I told so many about this application :D CUZ IT ROCKS 💜😍',
'希望有紅色的眼睛',
'saquen lo para samsung gala y ace porfavor',
'English translation!!!!!!',
'ola :)',
'好 很满意',
'功能少了点！',
'没有艾佛森的头戴啊😱',
'hi gys',
'脸萌总是莫名其妙地闪屏……',
'我觉得我姐的脸萌好玩',
'Test',
'希望有气泡~',
'我想要换肤色跟发色喔，程序员哥哥加油',
'建议有历史形象的功能喔~萌萌哒',
'纯白色的长袖T恤去哪儿了╯﹏╰',
'我觉得 库还是不多 要是能把表情 横向 纵向 拉长缩短就更好了',
'救加一些K-ON的角色吧！！',
'多弄一些发型啊！服装啊！嘴巴啊！眼睛啊！头饰啊！…………',
'把聲音整個去掉好嗎？吵死了，雖然關了，但自己又會莫名其妙開',
'好好玩',
'摸摸头像我觉得啊啊啊啊啊啊啊啊',
'嘻嘻嘻嘻',
'我拼不出我的头，好忧伤',
'请把类别和各种类別里的物品尽量都增加一些，谢谢了!',
'老是按不了',
'太少衫啦…',
'how can i change the language of the app?',
'我等了这么久，为什么就没有拿着咖啡杯，茶杯，和红酒杯的动作呢？？只有拿啤酒杯！！',
'有基德的衣服却没有帽子！',
'不错……很干净……',
'竟然还有剑三破军的衣服和帽子，赞一个，不过我觉得少了禅杖',
'comment on remet les trucs pour changer de style de personnages ? appars sa l appli trop génial',
'luv this game',
'Louis',
'je t aime',
'wiii',
'你们的游戏蛮好玩的啊！能不能再添加一点项链首饰啥的？',
'忒好玩了',
'发型不够丰富建议添加动漫中角色的发型(*/ω＼*)【爱好】中还是太少了 建议添加一些链条啊什么的',
'I want send my picture by whatsapp no twitter or IG.',
'p',
'太少了。不够漂亮，不够萌。',
'안녕',
'::xh',
'什么jb玩意',
'要更新了吗?',
'神经病喔',
'里面的声音吓我一跳了诶',
'希望推出双人版',
'萌萌哒',
'你们在深圳吗？我也在',
'双人版呢?',
'什么时候推出专属礼物啊？',
'有宠物小精灵诶',
'i love it!',
'hi hi hi',
'can someone let me make them,a FaceQ please I m bored',
'if you make an avatar that looks like me on FaceQ I will love you forever',
'Where do I get it',
'...the App Store',
'如果肤色能改变就好拉',
'眼睛可以换色吗？',
'Can I join you?',
':>',
'best app ever',
'I super love this App is amazing!',
'気泡言葉を記入してくださいね　～',
'双子モード',
'イケメン',
'分かち合い',
'everyone has faceq layouts now omg',
'Genial genial genial',
'You should add freckles',
'These things adorable',
'RIGHTEOUS',
'FaceQ',
'辣条5毛一包',
'卡卡卡ka ka ka ka',
'麻痹，卡到飞起',
'不好玩!',
'so cute!',
'How can i change the idiom? I can t understand anything',
'點解眼镜冇顏色選？',
'está dando erro toda hora',
'是否考虑拍照添加',
'Ola',
'我是个动漫控 黑岩射手 左眼前的蓝色火焰很炫，我希望我的QQ头像前也可以有，请满足我的小愿望吧',
'挺逗的，希望继续升级！',
'3 people',
'Haters gonna hate hate hate hate hate',
'☁☀(*´ω｀*)＼(☆o☆)／o(^o^)o(｀ω´)(≧∇≦)b(≧∇≦*)',
'希望历史形象是翻页的，不只局限于这五幅画。望采纳。',
'hola :) hello :)',
'如果发型再多一点就更完美了， 比如像喜羊羊与灰太狼的发型。。 望采纳(^з^)',
'هههههه',
'Can you do my faceQ With my poco?',
'BEST APP EVER',
'iron man',
'tienes que poner para que te saquen una foto y la ponga auntomaticamente',
'l want temari s hair please!!!!!',
'my brother ♥',
'马勒戈壁',
'内什么，脸萌貌似有bug啊，有时候刚开始拼脸它就自动退出了',
'太假了啊。。',
'对不起啊，发错了',
'来个裤子',
'THIS APP IS AWESOME AND SOOO ADDICTING',
'建议眼睛里面加轮回眼。可以配耳环项链。帽子的款式多一些。在加上白胡子的胡子。',
'mi faceq es el mejor',
'要是有全家福模式就好了',
'有没有海贼王霸气系列',
'什么意思啊，自动退出搞叼是么',
'回话呀！',
'能加到qq个性表情里去，我刚给你们发了个邮件才发现这里有意见反馈，汗😓。。。',
'♔♔♞♞♣♧☎☏☎☏',
'我在里面发现小樱的衣服，但是没有小樱的头发',
'我以为是拿照片自动生成的呢',
'头像加1，要追随潮流啊',
'话说，强迫症头像你们赶紧更新啊！！！！',
'脸萌真的棒棒哒！(๑•̀ㅂ•́)و✧',
'有些男人是不穿衣服的',
'猥琐哥',
'搞个发真人照片过去替我们搞 可以收2-4块手机费 这样最好',
'ㄘㄍㄊㄛㄧㄟㄟㄙㄛㄒㄍㄠ',
'进不了，你们要读取地理位置干嘛',
'无趣的游戏啊',
'你爷，老更新！！！',
'整点动态的！',
'holaaaa:)',
'为啥没有狼人的牙齿，爪子，眼睛',
'宇智波斑'
];